# 실습 1

In [1]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [4]:
iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = svm.SVC()
clf= GridSearchCV(svc, parameters)
clf.fit(iris.data, iris.target)
sorted(clf.cv_results_.keys())
print('Best score: %0.3f' % clf.best_score_)
print('Best parameters set:')
best_parameters= clf.best_estimator_.get_params()
for param_name in sorted(parameters.keys()):
    print('\t%s: %r' % (param_name, best_parameters[param_name]))

Best score: 0.980
Best parameters set:
	C: 1
	kernel: 'linear'


# 실습 2

In [ ]:
#데이터 탐색

In [2]:
import pandas as pd
df= pd.read_csv('./train.tsv', header=0, delimiter='\t')
print(df.count())
print(df.head())
print(df['Phrase'].head(10))
print(df['Sentiment'].describe())

PhraseId      156060
SentenceId    156060
Phrase        156060
Sentiment     156060
dtype: int64
   PhraseId  SentenceId                                             Phrase  \
0         1           1  A series of escapades demonstrating the adage ...   
1         2           1  A series of escapades demonstrating the adage ...   
2         3           1                                           A series   
3         4           1                                                  A   
4         5           1                                             series   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2  
0    A series of escapades demonstrating the adage ...
1    A series of escapades demonstrating the adage ...
2                                             A series
3                                                    A
4                                               series
5    of escapades demonstrating the adage that what...
6             

In [13]:
#리뷰반응분포확인
print(df['Sentiment'].value_counts())
print(df['Sentiment'].value_counts()/df['Sentiment'].count())

2    79582
3    32927
1    27273
4     9206
0     7072
Name: Sentiment, dtype: int64
2    0.509945
3    0.210989
1    0.174760
4    0.058990
0    0.045316
Name: Sentiment, dtype: float64


In [14]:
#로지스틱 회귀

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV


In [16]:
df= pd.read_csv('./train.tsv', header=0, delimiter='\t')
X, y = df['Phrase'], df['Sentiment'].values
X_train, X_test, y_train, y_test= train_test_split(X, y, train_size=0.5)
pipeline = Pipeline([
('vect', TfidfVectorizer(stop_words='english')),
('clf', LogisticRegression())
])

In [17]:
parameters = {
'vect__max_df': (0.25, 0.5),
'vect__ngram_range': ((1, 1), (1, 2)),
'vect__use_idf': (True, False),
'clf__C': (0.1, 1, 10),
}

In [18]:
grid_search = GridSearchCV(pipeline, parameters, n_jobs=-1, verbose=1, scoring='accuracy')
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


C:\Users\silvi\Anaconda3\envs\basic\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(estimator=Pipeline(steps=[('vect',
                                        TfidfVectorizer(stop_words='english')),
                                       ('clf', LogisticRegression())]),
             n_jobs=-1,
             param_grid={'clf__C': (0.1, 1, 10), 'vect__max_df': (0.25, 0.5),
                         'vect__ngram_range': ((1, 1), (1, 2)),
                         'vect__use_idf': (True, False)},
             scoring='accuracy', verbose=1)

In [20]:
print('Best score: %0.3f' %grid_search.best_score_)
print('Best parameters set:')
best_parameters = grid_search.best_estimator_.get_params()
for param_name in sorted(parameters.keys()):
    print('t%s: %r' %(param_name, best_parameters[param_name]))

Best score: 0.620
Best parameters set:
tclf__C: 10
tvect__max_df: 0.25
tvect__ngram_range: (1, 2)
tvect__use_idf: False


In [21]:
#각 부류별로 저밀도, 재현율, F1점수와 전체적인 정확도를 계산

In [22]:
predictions = grid_search.predict(X_test)
print('Accuracy: %s' % accuracy_score(y_test, predictions))
print('Confusion Matrix:')
print(confusion_matrix(y_test, predictions))
print('Classification Report:')
print(classification_report(y_test, predictions))

Accuracy: 0.6273997180571576
Confusion Matrix:
[[  908  1786   744   109     7]
 [  744  5832  6353   703    34]
 [  191  3244 32527  3633   208]
 [   28   450  6683  8112  1201]
 [    3    47   520  2386  1577]]
Classification Report:
              precision    recall  f1-score   support

           0       0.48      0.26      0.33      3554
           1       0.51      0.43      0.47     13666
           2       0.69      0.82      0.75     39803
           3       0.54      0.49      0.52     16474
           4       0.52      0.35      0.42      4533

    accuracy                           0.63     78030
   macro avg       0.55      0.47      0.50     78030
weighted avg       0.61      0.63      0.61     78030



# 실습3

In [6]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [7]:
iris = load_iris()
#입력: 꽃의너비와높이
X = iris.data[:,(0, 1)]
#출력: iris setosa인지아닌지
y = (iris.target== 0).astype(np.int)

C:\Users\silvi\AppData\Local\Temp\ipykernel_19400\3554815961.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = (iris.target== 0).astype(np.int)


In [8]:
percept = Perceptron(random_state=32)
percept.fit(X, y)
percept.score(X, y)

0.8533333333333334

In [9]:
#데이터를 훈련세트와 테스트세트로 구분하여 훈련시킨 후, 테스트세트의 정밀도, 재현율, F1점수 구하기

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

In [28]:
print(len(x_train), len(x_test))

120 30


In [30]:
#데이터 훈련
percept = Perceptron(random_state=32)
percept.fit(x_train, y_train)
percept.score(x_train, y_train)

1.0

In [31]:
#테스트데이터
percept.score(x_test, y_test)

0.9666666666666667

In [36]:
predictions = percept.predict(x_test)
print('Accuracy: %s' % accuracy_score(y_test, predictions))
print('Confusion Matrix:')
print(confusion_matrix(y_test, predictions))
print('Classification Report:')
print(classification_report(y_test, predictions))

Accuracy: 0.9666666666666667
Confusion Matrix:
[[20  0]
 [ 1  9]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.98        20
           1       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.98      0.95      0.96        30
weighted avg       0.97      0.97      0.97        30



# 실습 4

In [1]:
#SVM을 이용한 문자 분류
from sklearn.datasets import fetch_openml
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

In [2]:
mnist=fetch_openml('mnist_784',version=1,cache=True)
X=mnist['data']
y=mnist['target'].astype(np.uint8)

C:\Users\silvi\Anaconda3\envs\basic\lib\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
#훈련데이터와테스트데이터분리
X_train=X[:600]
y_train=y[:600]
X_test=X[600:700]
y_test=y[600:700]

### a. 선형 svm 분류기로 학습
```
svc(kernel = 'linear')
or
LinearSVC(random_state = 42)
```

In [4]:
#선형SVM 분류기로학습
lin_clf=LinearSVC(random_state=42)
lin_clf.fit(X_train,y_train)

LinearSVC(random_state=42)

In [5]:
y_pred=lin_clf.predict(X_train)
accuracy_score(y_train,y_pred)

1.0

In [6]:
from sklearn.svm import SVC

#SVM 커널함수를이용하여학습
svm_clf= SVC(kernel='rbf', gamma=0.01, C=100)
lin_clf.fit(X_train,y_train)

LinearSVC(random_state=42)

In [7]:
y_pred=lin_clf.predict(X_train)
accuracy_score(y_train,y_pred)

1.0

### b. 그리드 탐색을 이용하여 최적의 parameter 찾기

```
파라메터는gamma={0.01, 0.03, 0.1, 0.3, 1), C={0.1, 0.3, 1, 3, 10, 30)
.
커널함수는기본rbf를이용
```

In [8]:
from sklearn.svm import SVC
#grid search

parameters = {
'gamma': (0.01, 0.03, 0.1, 0.3, 1),
'C': (0.1, 0.3, 1, 3, 10, 30),
'kernel' : ['rbf'],
}

In [10]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(SVC(), parameters, n_jobs=-1, verbose=1, scoring='accuracy')
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.1, 0.3, 1, 3, 10, 30),
                         'gamma': (0.01, 0.03, 0.1, 0.3, 1),
                         'kernel': ['rbf']},
             scoring='accuracy', verbose=1)

In [11]:
print('Best score: %0.3f' %grid_search.best_score_)
print('Best parameters set:')
best_parameters = grid_search.best_estimator_.get_params()
for param_name in sorted(parameters.keys()):
    print('t%s: %r' %(param_name, best_parameters[param_name]))

Best score: 0.132
Best parameters set:
tC: 0.1
tgamma: 0.01
tkernel: 'rbf'


In [13]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
#각 부류별로 저밀도, 재현율, F1점수와 전체적인 정확도를 계산
predictions = grid_search.predict(X_test)
print('Accuracy: %s' % accuracy_score(y_test, predictions))
print('Confusion Matrix:')
print(confusion_matrix(y_test, predictions))
print('Classification Report:')
print(classification_report(y_test, predictions))

Accuracy: 0.11
Confusion Matrix:
[[ 0 11  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0 13  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0  0  0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.11      1.00      0.20        11
           2       0.00      0.00      0.00        12
           3       0.00      0.00      0.00         8
           4       0.00      0.00      0.00        12
           5       0.00      0.00      0.00        11
           6       0.00      0.00      0.00         9
           7       0.00      0.00      0.00        13
           8       0.00      0.00      0.00         6
           9       0.00      0.00      0.00         7

    accuracy     

C:\Users\silvi\Anaconda3\envs\basic\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\silvi\Anaconda3\envs\basic\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\silvi\Anaconda3\envs\basic\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
